<a href="https://colab.research.google.com/github/kasdaniel/DSC110.2/blob/main/In_class_week8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Prep for Machine Learning/Prediction**

In [2]:
#import pandas
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [30]:
df = pd.read_csv('https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv')

In [4]:
df.head ()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN

**1-Filtering**

In [31]:
df=df[df['age']>= 18].copy ()

In [7]:
df['age'].min()

18.0

In [10]:
df.shape

(8153, 11)

**2-dropping columns**

In [11]:
df= df.drop(columns=['id', 'hba1c','fasting_glucose'])

In [12]:
df.shape

(8153, 8)

In [13]:
df.head()

,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes
0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0
1,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0
2,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0
6,1.0,43.0,1.0,2.0,NaN,NaN,NaN,2.0
7,2.0,65.0,3.0,3.0,NaN,NaN,NaN,2.0

**3-Label Mapping**

In [32]:
#Dictionaries
gender_map     = {1.0: 'Male', 2.0: 'Female'}
race_map       = {1.0: 'Mexican American', 2.0: 'Other Hispanic',
                  3.0: 'White', 4.0: 'Black',
                  6.0: 'Asian', 7.0: 'Other'}
education_map  = {1.0: 'Less than 9th', 2.0: '9-11th grade',
                  3.0: 'High school',   4.0: 'Some college',
                  5.0: 'College grad',  9.0: 'Do not know'}

#df['gender']         = df['gender'].map(gender_map)
#df['race_ethnicity'] = df['race_ethnicity'].map(race_map)
#df['education']      = df['education'].map(education_map)

In [33]:
df['gender']=df['gender'].map(gender_map)

In [25]:
df['gender'].head()

0      Male
1      Male
2    Female
3    Female
4      Male
Name: gender, dtype: object

In [26]:
df['race_ethnicity']= df['race_ethnicity'].map(race_map)

In [27]:
df['race_ethnicity']

0                 Asian
1                 White
2        Other Hispanic
3                 Other
4                 White
              ...
11928    Other Hispanic
11929             Black
11930    Other Hispanic
11931    Other Hispanic
11932             White
Name: race_ethnicity, Length: 11933, dtype: object

In [34]:
df['education']= df['education'].map(education_map)

In [35]:
df['education'].head()

0    College grad
1    College grad
2     High school
6    9-11th grade
7     High school
Name: education, dtype: object

**4-Missing Values**

In [37]:
#check for missing values
df.isna().sum()

id                    0
gender                0
age                   0
race_ethnicity        0
education           359
bmi                1918
height_cm          1891
systolic_bp        2030
has_diabetes          3
hba1c              2151
fasting_glucose    4824
dtype: int64

In [38]:
df['bmi'] = df['bmi'].fillna(df['bmi'].mean())

In [39]:
df.isna().sum()

id                    0
gender                0
age                   0
race_ethnicity        0
education           359
bmi                   0
height_cm          1891
systolic_bp        2030
has_diabetes          3
hba1c              2151
fasting_glucose    4824
dtype: int64

In [40]:
df['height_cm']   = df['height_cm'].fillna(df['height_cm'].mean())
df['systolic_bp'] = df['systolic_bp'].fillna(df['systolic_bp'].mean())

In [41]:
df.isna().sum()

id                    0
gender                0
age                   0
race_ethnicity        0
education           359
bmi                   0
height_cm             0
systolic_bp           0
has_diabetes          3
hba1c              2151
fasting_glucose    4824
dtype: int64

In [42]:
df = df.dropna(subset=['education']).copy()

**5-Defining the target variable**

In [43]:
df = df[df['has_diabetes'].isin([1.0, 2.0])].copy()

In [49]:
df['has_diabetes'] = df['has_diabetes'].map({1.0: 1, 2.0: 0})

In [50]:
df.head()

,id,age,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose,gender_Female,gender_Male,...,race_ethnicity_3.0,race_ethnicity_4.0,race_ethnicity_6.0,race_ethnicity_7.0,education_9-11th grade,education_College grad,education_Do not know,education_High school,education_Less than 9th,education_Some college
0,130378.0,43.0,27.000000,179.500000,135.000000,NaN,5.6,113.0,False,True,...,False,False,True,False,False,True,False,False,False,False
1,130379.0,66.0,33.500000,174.200000,121.000000,NaN,5.6,99.0,False,True,...,True,False,False,False,False,True,False,False,False,False
2,130380.0,44.0,29.700000,152.900000,111.000000,1.0,6.2,156.0,True,False,...,False,False,False,False,False,False,False,True,False,False
6,130384.0,43.0,29.659326,166.954982,122.561653,NaN,NaN,NaN,False,True,...,False,False,False,False,True,False,False,False,False,False
7,130385.0,65.0,29.659326,166.954982,122.561653,NaN,NaN,NaN,True,False,...,True,False,False,False,False,False,False,True,False,False

In [51]:
df.shape

(7523, 22)

**6-One-Hot Encoding**

In [52]:
df = pd.get_dummies(df,columns=['gender', 'race_ethnicity', 'education'],
                    drop_first=True)

KeyError: "None of [Index(['gender', 'race_ethnicity', 'education'], dtype='object')] are in the [columns]"

In [53]:
df.head()

,id,age,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose,gender_Female,gender_Male,...,race_ethnicity_3.0,race_ethnicity_4.0,race_ethnicity_6.0,race_ethnicity_7.0,education_9-11th grade,education_College grad,education_Do not know,education_High school,education_Less than 9th,education_Some college
0,130378.0,43.0,27.000000,179.500000,135.000000,NaN,5.6,113.0,False,True,...,False,False,True,False,False,True,False,False,False,False
1,130379.0,66.0,33.500000,174.200000,121.000000,NaN,5.6,99.0,False,True,...,True,False,False,False,False,True,False,False,False,False
2,130380.0,44.0,29.700000,152.900000,111.000000,1.0,6.2,156.0,True,False,...,False,False,False,False,False,False,False,True,False,False
6,130384.0,43.0,29.659326,166.954982,122.561653,NaN,NaN,NaN,False,True,...,False,False,False,False,True,False,False,False,False,False
7,130385.0,65.0,29.659326,166.954982,122.561653,NaN,NaN,NaN,True,False,...,True,False,False,False,False,False,False,True,False,False

In [54]:
numeric_cols = ['age', 'bmi', 'height_cm', 'systolic_bp']
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [55]:
print(round(df['age'].mean(),2))

0.0

In [56]:
df['age'].std()

1.0000664694739656

**8-Train/Test Split

In [57]:
X = df.drop(columns=['has_diabetes'])
y = df['has_diabetes']

In [58]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [59]:
X_train.head()

,id,age,bmi,height_cm,systolic_bp,hba1c,fasting_glucose,gender_Female,gender_Male,race_ethnicity_1.0,...,race_ethnicity_3.0,race_ethnicity_4.0,race_ethnicity_6.0,race_ethnicity_7.0,education_9-11th grade,education_College grad,education_Do not know,education_High school,education_Less than 9th,education_Some college
6225,136603.0,0.321165,0.183891,-1.310308,0.446166,5.5,83.0,True,False,False,...,True,False,False,False,False,False,False,True,False,False
8518,138896.0,0.776425,-1.080948,-0.062021,-0.739931,5.0,83.0,True,False,False,...,True,False,False,False,False,False,False,True,False,False
5532,135910.0,0.548795,1.885958,1.061437,0.633444,NaN,NaN,True,False,False,...,False,True,False,False,False,True,False,False,False,False
7314,137692.0,1.459315,-0.009844,0.000959,-0.018182,NaN,NaN,True,False,False,...,True,False,False,False,False,False,False,False,True,False
9913,140291.0,-0.987708,-0.987256,0.494034,-0.178096,5.7,92.0,False,True,False,...,False,False,False,False,False,False,False,False,True,False